nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET','PATCH', 'DELETE','OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%', '%env(FRONT_URL)%']
